# -*- coding: utf-8 -*-
"""Emotion _Detection_Training

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1APQAlW6nu_MriwtYGP_i-rg4lPQuZ7yi
"""

!pip install tensorflow transformers torch nltk pandas numpy scikit-learn plotly google-generativeai

!ls /content/

import pandas as pd

train_df = pd.read_csv(
    '/content/train.txt',
    sep=';',
    names=['text', 'emotion']
)

train_df.head()

X = train_df['text']
y = train_df['emotion']

print(X.head())
print(y.head())

from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
y = encoder.fit_transform(y)

print(y[:10])

print(encoder.classes_)

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Create tokenizer
tokenizer = Tokenizer(num_words=10000)
tokenizer.fit_on_texts(X)

# Convert text to sequences
sequences = tokenizer.texts_to_sequences(X)

# Pad sequences
X = pad_sequences(sequences, maxlen=100)

print(X.shape)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training data shape:", X_train.shape)
print("Testing data shape:", X_test.shape)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Bidirectional, LSTM, Dense, Dropout

model = Sequential([
    Embedding(input_dim=10000, output_dim=128),

    Bidirectional(LSTM(64)),

    Dropout(0.5),

    Dense(64, activation='relu'),

    Dense(6, activation='softmax')
])

model.compile(
    loss='sparse_categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

model.summary()

history = model.fit(
    X_train,
    y_train,
    epochs=5,
    batch_size=32,
    validation_data=(X_test, y_test)
)

model.save('bilstm_model.h5')

print("Model saved successfully!")

import pickle

# Save tokenizer
with open('tokenizer.pkl', 'wb') as f:
    pickle.dump(tokenizer, f)

# Save label encoder
with open('label_encoder.pkl', 'wb') as f:
    pickle.dump(encoder, f)

print("Tokenizer and Label Encoder saved successfully!")

sample_text = ["I am very happy because I completed my project"]

sequence = tokenizer.texts_to_sequences(sample_text)
padded = pad_sequences(sequence, maxlen=100)

prediction = model.predict(padded)

predicted_class = prediction.argmax(axis=1)[0]

emotion = encoder.inverse_transform([predicted_class])

print("Predicted Emotion:", emotion[0])

# Predict on test data
y_pred = model.predict(X_test)

# Convert probabilities to class labels
y_pred_classes = np.argmax(y_pred, axis=1)

print("Predictions completed successfully!")

import plotly.express as px
import pandas as pd

# Convert predicted labels back to emotion names
emotion_labels = encoder.inverse_transform(y_pred_classes)

# Create DataFrame
results_df = pd.DataFrame({
    'Emotion': emotion_labels
})

# Count emotions
emotion_counts = results_df['Emotion'].value_counts().reset_index()
emotion_counts.columns = ['Emotion', 'Count']

# Create chart
fig = px.bar(
    emotion_counts,
    x='Emotion',
    y='Count',
    title='Emotion Distribution',
    color='Emotion'
)

fig.show()

from datetime import datetime

# Create logs DataFrame
logs_df = pd.DataFrame({
    'Predicted_Emotion': emotion_labels
})

# Add timestamp
logs_df['Timestamp'] = datetime.now()

# Save to CSV
logs_df.to_csv('emotion_logs.csv', index=False)

print("Emotion logs saved successfully!")

def learning_support(emotion):

    if emotion == 'sadness':
        return "You seem sad. Take a short break and stay positive."

    elif emotion == 'anger':
        return "You seem frustrated. Try revising the topic slowly and relax."

    elif emotion == 'fear':
        return "Don't worry. Practice more and build confidence."

    elif emotion == 'joy':
        return "Great! You are feeling happy. Continue your learning journey."

    elif emotion == 'love':
        return "You are feeling positive. Keep learning with enthusiasm."

    elif emotion == 'surprise':
        return "You seem surprised. Explore more about this topic."

    elif emotion == 'confused':
        return "You seem confused. Revise the concepts and watch tutorial videos."

    elif emotion == 'frustrated':
        return "Take a short break, relax, and try solving simpler problems first."

    elif emotion == 'curious':
        return "Great curiosity! Explore advanced topics and experiment with new ideas."

    elif emotion == 'confident':
        return "Excellent! You are confident. Move on to more challenging topics."

    elif emotion == 'bored':
        return "Try interactive learning methods such as videos, quizzes, or projects."

    else:
        return "Stay motivated and continue learning."

emotion = "joy"

print("Emotion:", emotion)
print("AI Guidance:", learning_support(emotion))

user_text = input("Enter how you feel: ")

# Convert text to sequence
sequence = tokenizer.texts_to_sequences([user_text])

# Pad sequence
padded = pad_sequences(sequence, maxlen=100)

# Predict emotion
prediction = model.predict(padded)

predicted_class = np.argmax(prediction)

emotion = encoder.inverse_transform([predicted_class])[0]

# Display results
print("\nPredicted Emotion:", emotion)
print("AI Guidance:", learning_support(emotion))

user_text = input("Enter how you feel: ")

# Convert text to sequence
sequence = tokenizer.texts_to_sequences([user_text])

# Pad sequence
padded = pad_sequences(sequence, maxlen=100)

# Predict emotion
prediction = model.predict(padded)

predicted_class = np.argmax(prediction)

emotion = encoder.inverse_transform([predicted_class])[0]

# Confidence Score
confidence = np.max(prediction) * 100

# Display results
print("\nPredicted Emotion:", emotion)
print("Confidence Score: {:.2f}%".format(confidence))
print("AI Guidance:", learning_support(emotion))

# Find top 2 emotions
top_2 = prediction[0].argsort()[-2:][::-1]

primary_emotion = encoder.inverse_transform([top_2[0]])[0]
secondary_emotion = encoder.inverse_transform([top_2[1]])[0]

print("Primary Emotion:", primary_emotion)
print("Secondary Emotion:", secondary_emotion)

!pip install -q google-generativeai

import google.generativeai as genai

print("Gemini library imported successfully!")

import google.generativeai as genai

# Configure Gemini API
genai.configure(api_key="YOUR_API_KEY")

# Load Gemini model
gemini_model = genai.GenerativeModel("gemini-1.5-flash")

print("Gemini configured successfully!")

import google.generativeai as genai

genai.configure(api_key="PASTE_YOUR_API_KEY_HERE")

gemini_model = genai.GenerativeModel("gemini-1.5-flash")

print("Gemini configured successfully!")

import google.generativeai as genai

genai.configure(api_key="PASTE_YOUR_API_KEY_HERE")

gemini_model = genai.GenerativeModel("gemini-1.5-flash")

print("Gemini configured successfully!")

for m in genai.list_models():
    if "generateContent" in m.supported_generation_methods:
        print(m.name)

# Load Gemini model
gemini_model = genai.GenerativeModel('models/gemini-2.5-flash')

prompt = f"""
The student is feeling {emotion}.

Provide short motivational learning guidance in 2-3 lines.
"""

response = gemini_model.generate_content(prompt)

print("\nGemini AI Guidance:")
print(response.text)

!pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pickle
# import numpy as np
# import google.generativeai as genai
# 
# from tensorflow.keras.models import load_model
# from tensorflow.keras.preprocessing.sequence import pad_sequences
# 
# # Page Configuration
# st.set_page_config(
#     page_title="Emotion Detection & Learning Support Engine",
#     page_icon="😊",
#     layout="centered"
# )
# 
# # Load Model
# model = load_model('bilstm_model.h5')
# 
# with open('tokenizer.pkl', 'rb') as f:
#     tokenizer = pickle.load(f)
# 
# with open('label_encoder.pkl', 'rb') as f:
#     encoder = pickle.load(f)
# 
# # Gemini API Configuration
# genai.configure(api_key="AQ.Ab8RN6KCEwmj96kMrMF-GFwTl3htBHkXTl5ZBGlGCge0-LTlFA")
# 
# gemini_model = genai.GenerativeModel('models/gemini-2.5-flash')
# 
# # Streamlit UI
# st.title("😊 Emotion Detection & Learning Support Engine")
# 
# st.write("""
# This application detects emotions from user text and provides AI-powered learning guidance.
# """)
# 
# user_text = st.text_area(
#     "Enter how you feel:",
#     placeholder="Example: I am very happy because I completed my project"
# )
# 
# if st.button("Detect Emotion"):
# 
#     if user_text.strip() == "":
#         st.warning("Please enter some text.")
# 
#     else:
# 
#         # Text Preprocessing
#         sequence = tokenizer.texts_to_sequences([user_text])
#         padded = pad_sequences(sequence, maxlen=100)
# 
#         # Prediction
#         prediction = model.predict(padded)
# 
#         predicted_class = np.argmax(prediction)
# 
#         emotion = encoder.inverse_transform([predicted_class])[0]
# 
#         confidence = np.max(prediction) * 100
# 
#         # Mixed Emotion Detection
#         top_2 = prediction[0].argsort()[-2:][::-1]
# 
#         primary_emotion = encoder.inverse_transform([top_2[0]])[0]
#         secondary_emotion = encoder.inverse_transform([top_2[1]])[0]
# 
#         # Display Results
#         st.success(f"Predicted Emotion: {emotion}")
# 
#         st.info(f"Confidence Score: {confidence:.2f}%")
# 
#         st.write(f"### Primary Emotion: {primary_emotion}")
#         st.write(f"### Secondary Emotion: {secondary_emotion}")
# 
#         # Gemini Guidance
#         try:
#             prompt = f"""
#             The student is feeling {emotion}.
# 
#             Provide short motivational learning guidance in 2-3 lines.
#             """
# 
#             response = gemini_model.generate_content(prompt)
# 
#             st.subheader("🤖 Gemini AI Guidance")
#             st.write(response.text)
# 
#         except Exception as e:
#             st.error(f"Gemini Error: {e}")

!pip install transformers torch

from transformers import pipeline

classifier = pipeline(
    "text-classification",
    model="j-hartmann/emotion-english-distilroberta-base",
    top_k=None
)

print("BERT model loaded successfully!")

text = "I am very happy because I completed my project"

result = classifier(text)

print(result)

"""## BERT-based Emotion Analysis

A transformer-based emotion classification model
(j-hartmann/emotion-english-distilroberta-base)
was integrated to compare performance with the BiLSTM model.

### Sample Prediction

Input:
"I am very happy because I completed my project"

Output:
- Joy: 98.96%
- Surprise: 0.53%
- Sadness: 0.25%

### Model Comparison

| Model | Description |
|--------|-------------|
| BiLSTM | Deep learning sequence model trained on emotion dataset |
| BERT (DistilRoBERTa) | Pre-trained transformer model used for comparative emotion analysis |
"""